pipeline {
  agent any
  tools {
    maven "M3"
    jdk "jdk11"
  }
  stages {
    stage('Git fatch') {
      steps {
        echo 'Git fatch'
        git url: 'https://github.com/sudongst/spring-petclinic.git/',
          branch: 'main', credentialsId: 'gitCredential'
      }
    }
    stage('Maven Build') {
      steps {
        echo 'Maven Build'
        sh 'mvn -Dmaven.test.failure.ignore=true clean package'
      }
    }
    stage('Docker Image') {
      steps {
        echo 'Docker Image'
      }
    }
    stage('Image Push') {
      steps {
        echo 'Image Psuh'
      }
    }
    stage('Codedeploy Workload') {
      steps {
        echo 'Codedeploy Workload'
      }
    }
  }
}
